services:
  app:
    container_name: app
    build: ./app
    depends_on:
      - rabbitmq
      - mailhog

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ default port
      - '15672:15672' # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - rabbitmq
      - mailhog

volumes:
  rabbitmq_data:
